// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irouespyprcfaahmfolf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyb3Vlc3B5cHJjZmFhaG1mb2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTY2MTksImV4cCI6MjA2ODc5MjYxOX0.9U20rsqQ1x8sTJgvoG_pMsXLhE4xgV9QFe_doNbWpIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});